[package]
name = "cw-otc-common"

version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw20 = { workspace = true }
cw721 = { workspace = true }
